server:
  port: 8888
spring:
  security:
    user:
      name: admin
      password: 123456
mybatis-plus:
  mapper-locations: classpath*:/mapping/**/*Mapper.xml
jasypt:
  encryptor:
    password: EbfYkitspO235lKFNXI50JMXoaxZTKJ0
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
