spring:
  datasource:
    url: jdbc:p6spy:mysql://cdb-50qvvhyi.cd.tencentcdb.com:10130/bullseye_admin_kotlin?characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      username: root
      password: zhx8302812@#$
  redis:
    host: 118.24.91.197
    password: chris950602
uploadConfig:
  uploadPath: c:/aaa
  uploadUrl: http://localhost:8008
  prefix: /api/file
  storageType: local
aliConfig:
  OSS:
    endpoint: oss-cn-chengdu.aliyuncs.com
    accessKeyId: LTAI4G9UF8hRXgVck
    accessKeySecret: 3HLnwSC9LxnSXynR
    bucketName: admin
    domainName: https://ali-oos.com/
  video:
    accessKeyId: LTAI4GKQvL4JtzU9D8Y8KN3n
    accessKeySecret: oNe8rR2KpcwNYChtWc1fkawiHLsoVj
  pay:
    appId:
    privateKey:
    publicKey:
    domain: https://openapi.alipaydev.com/gateway.do
#    domain: https://openapi.alipay.com/gateway.do
    serverUrl:
    appCertPath:
    aliPayCertPath:
    aliPayRootCertPath:
tencentConfig:
  video:
    secretId: AKIDLQMEBtefcHfngQyHLFuITR1MSIwKOSDD
    secretKey: zh93lFTSGo685pKbO1YntrdCboxrGSZV
  wxPay:
    appId: 应用编号
    appSecret: appSecret 是 appId 对应的接口密码，微信公众号授权获取用户 openId 时使用
    mchId: 微信支付商户号
    partnerKey: API 密钥，微信商户后台配置
    certPath: apiclient_cert.p12 证书绝对路径，在微信商户后台下载
    domain: 外网访问项目的域名，支付通知、回调中会使用
