server:
  port: 8888
spring:
  security:
    user:
      name: admin
      password: 123456
mybatis:
  mapper-locations: classpath*:/mapping/*Mapper.xml
mapper:
  mappers: com.chris.bullseye.basemapper.BaseMapper
  not-empty: false
  identity: MYSQL
  before: true